import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './ui/components/navigation/Navigation'
import Footer from './ui/components/navigation/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WeCode',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
